version: '3'
services:
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=sqs
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - "4566:4566" # sqs
    networks:
      - localstack-network
networks:
  localstack-network:
    driver: bridge