name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack-light
        env:
          SERVICES: sqs
        ports:
          - "4566:4566" # sqs
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
        
    - name: AWS CLI installation
      uses: chrislennon/action-aws-cli@1.1

    - name: Build
      run: go build -v ./...

    - name: Test
      run: make test-execution
